name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo " Job was automatically triggered by  a $ {{ github.event_name}} event "
      - run: echo " Job is now running on a ${{runner.os}} server hosted by Github"
      - run: echo "Name of the repo is ${{github.repository}} and branch is ${{github.ref}}"
      - name: Check out code
      - uses: actions/checkout@v5
      - run: echo " the ${{github.repository}} has been cloned to the runner "
      - run: echo "the workflow is now ready to test your code on the runner"
      - name: List files in the repository
        run: |
          ls $ {{github.workspace}}
      - run: echo "job status is ${{job.status}}"
